#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo -e "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx start
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\n\
    server { \n\
        listen 80 default_server;\n\
        listen [::]:80 default_server;\n\
        server_name _;\n\
        return 301 http://www.example.com/new-page;\n\
    }/g' /etc/nginx/nginx.conf

