#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header
# custom header format:  `X-Served-By: hostname of the Nginx server


# updates the package list & install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# allows Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# create directory & set permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

# creates two files; default page and error page
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# modify default Nginx configuration; add rewrite rule, error_page & header
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/ permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

# modify default Nginx configuration; add custom header
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

sudo service nginx restart
