#!/usr/bin/env bash
# Installs and configures HAProxy version 2.6-stable (LTS) on lb-01 server running Ubuntu Focal (20.04 LTS)
# sends traffic to web-01 & web-02 using a roundrobin algorithm
# HAProxy managed via an init script


# update package and install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# update configuration file; bind port 80, roundrobin algorithm & two servers
echo '
frontend  jonyamagiri_frontend
        bind *:80
        mode http
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 66433-web-01 54.198.36.23:80 check
        server 66433-web-02 54.236.24.182:80 check
' >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy

# restart HAproxy service
sudo service haproxy restart
