#!/usr/bin/env bash
# Debugs & configures Nginx to run and listening on port 80
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
pid=$(cat /run/nginx.pid) && sudo kill "$pid"
