#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when 
# receiving a SIGQUIT or SIGTERM signal

del_file_exit()
{
	rm -f /var/run/myscript.pid
	exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; del_file_exit" SIGTERM
trap "del_file_exit" SIGQUIT

echo $BASHPID >> /var/run/myscript.pid

for (( ; ; ))
do
	echo "To infinity and beyond"
	sleep 2
done
