#!/usr/bin/env bash
# Manages the script 'manage_my_process'
# When passed the argument "start":
#	- Starts manage_my_process
#	- Creates a file containings its PID in /var/run/my_process.pid
#	- Displays "manage_my_process started"
# When passed the argument "stop":
#	- Stops manage_my_process
#	- Deletes the file /var/run/my_process.pid
#	- Displays "manage_my_process stopped"
# When passed the argument "restart":
#	- Stops manage_my_process
#	- Deletes the file /var/run/my_process.pid
#	- Starts manage_my_process
#	- Creates a file containing its PID in /var/run/my_process.pid
# 	- Displays "manage_my_process restarted"
# Displays "Usage: manage_my_process {start|stop|restart}"
#	if any other argument or no argument is passed

start_create_file()
{
	./manage_my_process &
	echo "$BASHPID" > /var/run/my_process.pid
}

stop_del_file()
{
	pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
}

if [ "$1" == "start" ]
then
	echo "manage_my_process started"
	start_create_file

elif [ "$1" == "stop" ]
then
	echo "manage_my_process stopped"
	stop_del_file

elif [ "$1" == "restart" ]
then
	echo "manage_my_process restarted"
	stop_del_file
	start_create_file

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
