#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration, displays
# Best School and then Hi on a new line.

message="Best School"
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	echo "$message"
	(( i++ ))
done
