#!/usr/bin/env bash
# loops from 1 to 10 using while loop and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

loop=1
while [ $loop -lt 11 ]
do
	if [ $loop == 4 ]; then
		echo $"bad luck"
	elif [ $loop == 8 ]; then
		echo $"good luck"
	else
		echo $"Best School"
	fi
	(( loop++ ))
done
