#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes using while loop:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
while [ $hours -lt 13 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	(( hours++ ))
done
