#!/usr/bin/env bash
# Configures the Nginx web server to run as the 'nginx' user and listen on port 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
